services:
  # BACKEND & FRONTEND (Monorepo setup)
  - type: web
    name: lab-system-full
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Defina o valor manualmente no painel do Render (ex: URL do Neon)
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://seu-frontend.vercel.app # URL que a Vercel vai te dar
